Mutation:
  type: object
  config:
    fields:
      AddStyle:
        type: StyleOutput
        resolve: "@=mutation('add_style', [args['input']])"
        args:
          input:
            type: StyleInput!
      AddBand:
        type: BandOutput
        resolve: "@=mutation('add_band', [args['input']])"
        args:
          input:
            type: BandInput!
      UpdateStyle:
        type: StyleOutput
        resolve: "@=mutation('update_style', [args['input']])"
        args:
          input:
            type: StyleUpdateInput!
      UpdateBand:
        type: BandOutput
        resolve: "@=mutation('update_band', [args['input']])"
        args:
          input:
            type: BandUpdateInput!
      DeleteStyle:
        type: StyleOutput
        resolve: "@=mutation('delete_style', [args['input']])"
        args:
          input:
            type: StyleDeleteInput!

StyleOutput:
  type: object
  config:
    description: "Style added"
    fields:
      id:
        type: "Int!"

BandOutput:
  type: object
  config:
    description: "Band added"
    fields:
      id:
        type: "Int!"

StyleInput:
  type: input-object
  config:
    description: "A music style"
    fields:
      name:
        type: "String"
        description: "Name"

BandInput:
  type: input-object
  config:
    description: "A music band"
    fields:
      name:
        type: "String"
        description: "Name"
      country:
        type: "String"
        description: "Country"

StyleUpdateInput:
  type: input-object
  config:
    description: "A music style"
    fields:
      name:
        type: "String"
        description: "Name"
      id:
        type: "Int!"

BandUpdateInput:
  type: input-object
  config:
    description: "A music band"
    fields:
      name:
        type: "String"
        description: "Name"
      country:
        type: "String"
        description: "Country"
      id:
        type: "Int!"

StyleDeleteInput:
  type: input-object
  config:
    description: "A music style"
    fields:
      id:
        type: "Int!"
