Mutation:
  type: object
  config:
    fields:
      AddStyle:
        type: StyleOutput
        resolve: "@=mutation('add_style', [args['input']])"
        args:
          input:
            type: StyleInput!
      UpdateStyle:
        type: StyleOutput
        resolve: "@=mutation('update_style', [args['input']])"
        args:
          input:
            type: StyleUpdateInput!
      DeleteStyle:
        type: StyleOutput
        resolve: "@=mutation('delete_style', [args['input']])"
        args:
          input:
            type: StyleDeleteInput!

StyleOutput:
  type: object
  config:
    description: "Style added"
    fields:
      id:
        type: "Int!"

StyleInput:
  type: input-object
  config:
    description: "A music style"
    fields:
      name:
        type: "String"
        description: "Name"

StyleUpdateInput:
  type: input-object
  config:
    description: "A music style"
    fields:
      name:
        type: "String"
        description: "Name"
      id:
        type: "Int!"

StyleDeleteInput:
  type: input-object
  config:
    description: "A music style"
    fields:
      id:
        type: "Int!"
