Query:
  type: object
  config:
    fields:
      style:
        type: "Style"
        args:
          id:
            type: "Int"
        resolve: "@=resolver('Style', [args])"
      styles_list:
        type: "StylesList"
        args:
          limit:
            type: "Int"
        resolve: "@=resolver('StylesList', [args])"
      band:
        type: "Band"
        args:
          id:
            type: "Int"
        resolve: "@=resolver('Band', [args])"
      bands_list:
        type: "BandsList"
        args:
          limit:
            type: "Int"
        resolve: "@=resolver('BandsList', [args])"